from pathlib import Path


questions = [
    {
        "key": "is_ai_system",
        "question": "Is this an AI system?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "ai_model_provider",
        "question": "AI model/provider",
        "type": "text",
        "answer": None,
        "auto_detect": True,
    },
    {
        "key": "cloud_provider",
        "question": "Cloud provider",
        "type": "text",
        "answer": None,
        "auto_detect": True,
    },
    {
        "key": "deployment_region",
        "question": "Deployment region",
        "type": "text",
        "answer": None,
        "auto_detect": True,
    },
    {
        "key": "hosting_country",
        "question": "Hosting country",
        "type": "text",
        "answer": None,
        "auto_detect": True,
    },
    {
        "key": "application_url",
        "question": "Application URL or domain",
        "type": "text",
        "answer": None,
        "auto_detect": True,
    },
    {
        "key": "api_endpoints",
        "question": "API endpoints",
        "type": "text",
        "answer": None,
        "auto_detect": True,
    },
    {
        "key": "serves_eu_users",
        "question": "Can users in the EU access this AI system?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "eu_market",
        "question": "Is this AI system sold or offered in the EU?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "eu_output_usage",
        "question": "Are AI decisions or outputs used in the EU?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "organization_location",
        "question": "Where is your organization located?",
        "type": "text",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "business_role",
        "question": "What is your role with respect to this AI system?",
        "type": "choice",
        "choices": [
            "Provider",
            "Deployer",
            "Importer",
            "Distributor",
            "Authorized Representative",
        ],
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "internal_only",
        "question": "Is this AI system used only within your organization?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "commercial_use",
        "question": "Is the AI system used for commercial purposes?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "research_only",
        "question": "Is this system used exclusively for research and development?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "military_use",
        "question": "Is this AI system intended for military or national security use?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "personal_use",
        "question": "Is this AI system intended solely for personal, non-professional use?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "open_source_model",
        "question": "Does this system use or distribute an open-source AI model?",
        "type": "confirm",
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "foundation_model",
        "question": "Foundation model (GPAI)",
        "type": "text",
        "answer": None,
        "auto_detect": True,
    },
    {
        "key": "application_domain",
        "question": "Which domain best describes this AI system?",
        "type": "choice",
        "choices": [
            "Healthcare",
            "Employment",
            "Education",
            "Finance",
            "Law Enforcement",
            "Critical Infrastructure",
            "Migration",
            "Public Services",
            "General Business",
            "Other",
        ],
        "answer": None,
        "auto_detect": False,
    },
    {
        "key": "end_user_country",
        "question": "Which country are your primary end users located in?",
        "type": "text",
        "answer": None,
        "auto_detect": False,
    },
]


def init():
    print("Initilizing the project")
    